sources: src
branches:
  branchingModel: GitFlow
  knownBranches:
  - name: refs/heads/master
    type: Main
    versioning:
      parentBranch: 
      tag: ''
      metadata: ''
  - name: refs/heads/develop
    type: Development
    versioning:
      parentBranch: refs/heads/master
      tag: 'dev-{commitcount}'
      metadata: ''
  - name: refs/heads/feature/*
    type: Feature
    versioning:
      parentBranch: refs/heads/develop
      tag: '{featurename}-{commitcount}'
      metadata: ''
  - name: refs/heads/release/*
    type: Release
    versioning:
      parentBranch: refs/heads/develop
      tag: 'rc-{commitcount}'
      metadata: ''
