sources: src
branches:
  branchingModel: GitFlow
  knownBranches:
  - name: refs/heads/master
    type: Main
    analysis:
      parentBranch: 
    versioning:      
      tag: ''
      metadata: ''
  - name: refs/heads/develop
    type: Development
    analysis:
      parentBranch: refs/heads/master
    versioning:      
      tag: 'dev-{commitcount}'
      metadata: ''
  - name: refs/heads/feature/*
    type: Feature
    analysis:
      parentBranch: refs/heads/develop
    versioning:      
      tag: '{featurename}-{commitcount}'
      metadata: ''
  - name: refs/heads/release/*
    type: Release
    analysis:
      parentBranch: refs/heads/develop
    versioning:      
      tag: 'rc-{commitcount}'
      metadata: ''
